### ISSUE TITLE
Support Opt-Out Cookie and forward Opt-Out iFrame

### ISSUE THREAD

**Issue by Findus23** [matomo-org/tracker-proxy#29] opened 2018-03-07 18:31 UTC
This is necessary for being able to use the proxy in a privacy sensitive way (e.g. for GDPR)
related to #24 and #23

**Comment by level420** [comment] 2018-04-06 14:25
@Findus23 see my recent PR https://github.com/matomo-org/tracker-proxy/pull/32
works as it should.
I suspect it can't be merged as the tests are failing. Waiting for @mattab to see why they are failing

**Comment by mattab** [comment] 2018-04-11 01:11
The goal of this issue is to provide a way for websites using the tracker proxy to also support the opt-out iframe. But likely the current design of the opt-out iframe, using a 3rd party, is not a suitable design solution, because the goal of tracker proxy is to not leak the 3rd party domain.

Therefore maybe we could provide another solution. it may be the easiest to allow people to use the standard opt-out iframe code, but instead of using `index.php?module=...` in the iframe URL they would replace and use `tracked-site.com/matomo-optout.php` and we'd include this file as part of the tracker proxy, so it proxies the requests and then sets the cookie on the tracker-site.com domain (instead of the hidden matomo instance URL). 
Thoughts?

**Comment by level420** [comment] 2018-04-11 06:35
I think the extra opt-out file `tracked-site.com/matomo-optout.php` is a good solution. I would go with it. 

One notice though regarding the EU GDPR: the privacy notices we will place on our websites also include instructions for the visitors how they can disable cookies in the browser.
So we come into the situation that a visitor not accepting cookies AND wanting to opt out from matomo tracking, is not able to do that because matomo is not able to set the "don't track me" cookie.

I wonder if it would be able for this situation to write the "don't track me" flag into the sqlite database of modern browsers as they are not cookies.

Another option would be to implicitly deal with visitors with disabled cookies as if they had the DNT headers set.

Weird situation.

**Comment by Findus23** [comment] 2018-04-11 06:40
As far as i know, GDPR Neger mentions cookies directly,but rather methods to save something into their Browser. So using localstorage instead of cookies doesn't change anyting. 

Maybe we should rather recommend enabling DNT

**Comment by level420** [comment] 2018-04-11 06:45
@Findus23 ah OK. Then I'd vote for enabling DNT in case the visitor disables cookies, or at least an option in matomo which could be enabled to do so. See this question on stackoverflow https://stackoverflow.com/a/6663901

**Comment by level420** [comment] 2018-04-24 17:52
@mattab @diosmosis any news on this?

**Comment by mattab** [comment] 2018-04-26 08:08
@level420 Please can you test #37 ?

**Comment by mattab** [comment] 2018-04-27 08:31
@level420 yep it's supposed to work. the iframe code hasn't changed

**Comment by level420** [comment] 2018-05-02 08:10
I'm having the following setup with apache 2.4 on centos 7.4 which fails somehow to set the opt out cookie. Note that besides the opt-out frame it works as expected.

The directory where `piwik.php`, `matomo-proxy.php`, `proxy.php`, `config.php` are served from is the relative path `/stat/` within webroot. This relative path is mounted via apache directive
```
Alias /stat/ "/data/somepath/piwik/"
```
into the webroot of several apache vhosts, including permission configuration etc. As said this works except the opt-out iframe.

The iframe itself is embedded correctly and does show the checkbox to uncheck for opting out. 
When clicking on that checkbox an additional browser window shows up and closes immediately again, but the opt-out cookie was not set, thus leaving the checkbox unchanged in the checked state.

The used code for the iframe is:
```html
<iframe
        style="border: 0; height: 200px; width: 600px;"
        src="/stat/matomo-proxy.php?module=CoreAdminHome&action=optOut&language=en&backgroundColor=&fontColor=&fontSize=&fontFamily="
        >
```
Another point could be about what is needed to be configured in `config.php` for `$PROXY_URL`. As said, I'm using all the tracker proxy code from the relative path `/stat/` and therefore I thought I need to configure this to
```php
$PROXY_URL = '/stat/';
```
And one last point: The comment/doc in `config.php` seems to be incomplete regarding `$PROXY_URL`. It seems to be interrupted in the midth of the explanation: https://github.com/matomo-org/tracker-proxy/blob/opt-out/config.php.example#L13-L14

So I guess that I need help here.

**Comment by level420** [comment] 2018-05-02 10:43
In addition here is my tracking code for the website:
```html
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  _paq.push(['disableCookies']);
  (function() {
    var u="//www.mywebsite.tld/stat/";
    _paq.push(['setTrackerUrl', u+piwik.php']);
    _paq.push(['setSiteId', '42']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type="text/javascript"; g.async=true; g.defer=true; g.src=u+"piwik.php"; s.parentNode.insertBefore(g,s);
  })();
</script>
```

**Comment by level420** [comment] 2018-05-02 13:34
So in the end I've got it to work, but it's far away from being perfect:

The problem why I didn't got it to work was that for opt out iframe to be able to set the opt out cookie it needs to get a piwik_sess cookie which is obviously needed for the opt out proxy to communicate with the piwik instance.

My test webseite was only available insecure over http:// while my matomo instance is available via https://. Let's name it www.mysite.tld
This lead to the fact that the matomo instance tried to set a secure cookie called PIWIK_SESS which was available to https://www.mysite.tld but not to http://www.mysite.tld. For this reason the opt out did not succeed because it seems that the cookie PIWIK_SESS is needed for the communication between the site and the matomo instance.

It started working as soon as I've switched over to https.

But now I have another question: why is the PIWIK_SESS needed at all?
Couldn't this be somehow omitted by the opt out proxy?

**Comment by diosmosis** [comment] 2018-05-02 14:00
I don’t think the PIWIK_SESSID should be needed, if it is that might be some kind of regression. I’ll look into this today, thanks for the detailed comments!

**Comment by level420** [comment] 2018-05-02 14:04
@diosmosis would opt out also work if I'm setting on the site myself a cookie called `piwik_ignore` with value `ignore`? This would simplify the whole process as I'd then create my own opt out dialog.

**Comment by diosmosis** [comment] 2018-05-02 16:46
@level420 It has to be set on the same domain as your matomo, so it's possible if you can achieve that. As long as it gets sent to your matomo tracker endpoint, matomo will detect it. (Side note: this means if your tracker endpoint is a proxy, this project or something else, the proxy has to forward it, or matomo won't see it.)

**Comment by diosmosis** [comment] 2018-05-02 21:04
@level420 So it looks like the session ID is required to be set for the opt out form in Matomo. There is a nonce used to verify the form submit that occurs when a user opts out. The generated nonce is stored in the session, so as it works now, PIWIK_SESSID is required. (CC @mattab)

I tested via SSL and was able to reproduce your issue with the tracker. Will update my PR with a fix.

**Comment by level420** [comment] 2018-05-03 08:08
@diosmosis @mattab 

Regarding the need of `PIWIK_SESSID`: the bad is that this cookie is set when you opt out being tracked by matomo. So this may lead to the people not trusting us that the opt out really happens if the `PIWIK_SESSID` cookie is present.

Regarding creation of the `piwik_ignore` cookie: this cookie is set for the domain of my site, `www.mysite.tld`. Is it enough to create that cookie myself, within my own php or whatever backend code with no call to the matomo instance involved? Is a value `ignore` sufficient for this?

**Comment by diosmosis** [comment] 2018-05-03 17:30
@level420 The `piwik_ignore` cookie must be sent to your matomo instance, otherwise matomo will not be able to detect it and ignore the request: https://github.com/matomo-org/matomo/blob/82a9b1b0a01dc20928d50134233e167f0116472d/core/Tracker/VisitExcluded.php#L95. So if your matomo is on the same domain as your site, then it should work, but to test you should check that the cookie is sent in requests to your `piwik.php` endpoint.

That said, it might be a good idea to also support the cookie sent on the site. Then we could detect it in `piwik.js` and never send a request in the first place, which would have another benefit of reducing load. CC @mattab

**Comment by diosmosis** [comment] 2018-05-07 02:08
@level420 fyi, there is now a PR on matomo to allow the creation of custom opt out forms that use first party cookies: https://github.com/matomo-org/matomo/pull/12829. If that gets in, you'll be able to opt a user out w/ your own form.

Note: the feature is built on top of the consent feature being added in 3.5.0. If you need to require explicit consent from users, you may not need an opt out form.

**Closed** 2018-05-12 01:10 UTC
